services:
  - name: backend
    path: sources/backend
    plan: free
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: APP_LLM_DEFAULT_MODEL
        value: x-ai/grok-4-fast
      - key: JAVA_OPTS
        value: "-Xmx512m"

  - name: frontend
    path: sources/frontend
    plan: free
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_API_URL
        sync: false
