server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Para que React/Vue/Vite funcione con rutas SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}
